# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

# Label changed port that the web server runs on
LABEL io.openshift.expose-services="8080:http" \
      io.k8s.description="A basic Apache HTTp Server child image, uses ONBUILD" \
      io.k8s.display-name="Apache HTTP Server" \
      io.openshift.tags="apache, httpd"

#Change port number in Apache HTTP server config file from default 80 to 8080
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf \
RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

#Change groupID and permissions of folders where web server process reads and writes files
RUN chgrp -R 0 /var/log/httpd /var/run.httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001

